### ISSUE TITLE
I want to use this program for education.

### ISSUE THREAD

**Issue by naoyashiga** [najibghadri/Tetris200lines#1]
I am TikToker for programming beginners in Japan.

https://www.tiktok.com/@coding_youtuber

I read this article you've posted four years ago.
https://codereview.stackexchange.com/questions/136406/tetris-in-c-in-200-lines

I like the concept of being able to make Tetris with a short program. This is a good programming resource for Japanese programming beginners.

I would like to introduce this program in a video. Could I introduce it?

**Comment by najibghadri** [comment]
Hey sorry didn't see this

**Comment by najibghadri** [comment]
You are free to do anything with this!

**Comment by najibghadri** [comment]
Sorry, only 1 year 1 month late

**Comment by najibghadri** [comment]
Good luck on the channel @naoyashiga

**Comment by naoyashiga** [comment]
@najibghadri Thanks you for reply. Many Japanese hit the like button.

https://www.tiktok.com/@coding_youtuber/video/6914195106169900290

**Comment by najibghadri** [comment]
Hahaha love it! 😄 ❤️
